#version 460 core

struct Vertex {
    float   positionX;
    float   positionY;
    float   positionZ;
    uint    packedColor;
    float   texCoordU;
    float   texCoordV;
    uint    packedOverlay;
    uint    packedLight;
    uint    packedNormal;
    uint    irisEntity_0;
    uint    irisEntity_1;
    float   irisMidCoordU;
    float   irisMidCoordV;
    uint    irisPackedTangent;
};

struct Transform {
    mat4    model;
    mat3    normal;
};

struct MeshInstance {
    uint    meshInfoIndex;
    uint    transformIndex;
    uint    bufferBaseIndex;
    uint    vertexOffset;
    uint    packedColor;
    uint    packedLight;
    uint    packedOverlay;
    uint    irisEntity_0;
    uint    irisEntity_1;
};

struct MeshInfo {
    uint    vertexOffset;
    uint    vertexLength;
};

struct WorkgroupInfo {
    uint    baseMeshInstance;
    uint    baseInvocation;
    uint    meshLength;
    uint    meshCount;
};

layout(local_size_x = 32) in;

layout(binding=0, std430) restrict readonly buffer MeshInfos {
    MeshInfo meshInfos[];
};

layout(binding=1, std430) restrict readonly buffer MeshVertices {
    Vertex meshVertices[];
};

layout(binding=2, std430) restrict readonly buffer MeshBufferBases {
    uint meshBufferBases[];
};

layout(binding=3, std430) restrict readonly buffer MeshTransforms {
    Transform meshTransforms[];
};

layout(binding=4, std430) restrict readonly buffer MeshInstances {
    MeshInstance meshInstances[];
};

layout(binding=5, std430) restrict readonly buffer WorkgroupInfos {
    WorkgroupInfo workgroupInfos[];
};

layout(binding=6, std430) restrict writeonly buffer OutputVertices {
    Vertex outputVertices[];
};

void main() {
    WorkgroupInfo workgroupInfo = workgroupInfos[gl_WorkGroupID.x];

    uint bucketInvocationIndex      = gl_LocalInvocationIndex   + workgroupInfo.baseInvocation;
    uint bucketMeshInstanceOffset   = bucketInvocationIndex     / workgroupInfo.meshLength;
    uint bucketMeshVertexOffset     = bucketInvocationIndex     % workgroupInfo.meshLength;

    if (bucketMeshInstanceOffset >= workgroupInfo.meshCount) {
        return;
    }

    MeshInstance meshInstance = meshInstances[workgroupInfo.baseMeshInstance + bucketMeshInstanceOffset];

    MeshInfo meshInfo = meshInfos[meshInstance.meshInfoIndex];

    if (bucketMeshVertexOffset >= meshInfo.vertexLength) {
        return;
    }

    uint        meshBufferBase  = meshBufferBases   [meshInstance   .bufferBaseIndex                        ];
    Transform   meshTransform   = meshTransforms    [meshInstance   .transformIndex                         ];
    Vertex      meshVertex      = meshVertices      [meshInfo       .vertexOffset + bucketMeshVertexOffset  ];

    vec4 colorInstance  = unpackUnorm4x8    (meshInstance   .packedColor);
    vec2 lightInstance  = unpackUnorm2x16   (meshInstance   .packedLight);
    vec4 colorMesh      = unpackUnorm4x8    (meshVertex     .packedColor);
    vec2 lightMesh      = unpackUnorm2x16   (meshVertex     .packedLight);

    vec4 colorOutput = colorInstance * colorMesh;
    vec2 lightOutput = max(lightInstance, lightMesh);

    vec4 positionMesh   = vec4          (meshVertex.positionX, meshVertex.positionY, meshVertex.positionZ, 1.0);
    vec4 tangentMesh    = unpackUnorm4x8(meshVertex.irisPackedTangent);
    vec4 normalMesh     = unpackUnorm4x8(meshVertex.packedNormal);

    mat3    meshMoodel3x3   = mat3(         meshTransform.model);
    vec4    positionOutput  =               meshTransform.model             * positionMesh;
    vec3    normalOutput    =               meshTransform.normal            * normalMesh    .xyz;
    vec3    tangentOutput   =               meshMoodel3x3                   * tangentMesh   .xyz;
    float   tangentWOutput  = (determinant( meshMoodel3x3) < 0 ? -1 : 1)    * tangentMesh   .w;

    uint outputIndex = meshBufferBase + meshInstance.vertexOffset + bucketMeshVertexOffset;

    outputVertices[outputIndex].positionX = positionOutput.x;
    outputVertices[outputIndex].positionY = positionOutput.y;
    outputVertices[outputIndex].positionZ = positionOutput.z;

    outputVertices[outputIndex].packedColor = packUnorm4x8(colorOutput);

    outputVertices[outputIndex].texCoordU = meshVertex.texCoordU;
    outputVertices[outputIndex].texCoordV = meshVertex.texCoordV;

    outputVertices[outputIndex].packedOverlay   = meshInstance.packedOverlay;
    outputVertices[outputIndex].packedLight     = packUnorm2x16(lightOutput);

    outputVertices[outputIndex].packedNormal = packSnorm4x8(vec4(normalize(normalOutput), 0.0));

    outputVertices[outputIndex].irisEntity_0 = meshInstances.irisEntity_0;
    outputVertices[outputIndex].irisEntity_1 = meshInstances.irisEntity_1;

    outputVertices[outputIndex].irisMidCoordU = meshVertex.irisMidCoordU;
    outputVertices[outputIndex].irisMidCoordV = meshVertex.irisMidCoordV;

    outputVertices[outputIndex].irisPackedTangent = packSnorm4x8(vec4(tangentOutput, tangentWOutput));
}